name: aoc2016day20
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util

library:
  source-dirs: src

executables:
  day20:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2016day20

tests:
  day20-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2016day20
    - hspec
