name: aoc2016day21
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util

library:
  source-dirs: .

executables:
  day21:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N